FROM golang:1.20-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /healthcare-api-integration ./cmd/api_integration/main.go

RUN find . -name "*.go" -type f -delete

CMD ["/healthcare-api-integration"]
