version: '3.4'

services:
  healthcaredb:
    image: postgres:latest
    container_name: healthcaredb
    hostname: healthcaredb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - healthcare
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 5
  healthcare-api:
    depends_on:
      healthcaredb:
        condition: service_healthy
    build:
      context: .
    container_name: healthcare-api
    hostname: healthcare-server
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    networks:
      - healthcare
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:${APP_PORT}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
  healthcare-api-integration:
    build:
      context: .
      dockerfile: ./Dockerfile.integration
    depends_on:
      healthcare-api:
        condition: service_healthy
    container_name: healthcare-api-integration
    hostname: healthcare-server-integration
    volumes:
      - .:/app
    ports:
      - ${APP_INTEGRATION_PORT}:${APP_INTEGRATION_PORT}
    networks:
      - healthcare
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  pg_data:

networks:
  healthcare:
    driver: bridge
